FROM apache/spark:3.5.3

USER root

RUN pip install --no-cache-dir \
    pyspark==3.5.3 \
    delta-spark==3.2.0

WORKDIR /app

COPY streaming /app/streaming
COPY configs /app/configs

CMD ["spark-submit", "/app/streaming/spark_streaming_job.py"]




