FROM apache/spark:3.5.3

USER root

WORKDIR /app

COPY streaming /app/streaming
COPY configs /app/configs

# ============================================================
# Delta Lake
# ============================================================

RUN curl -fL \
    https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar \
    -o /opt/spark/jars/delta-spark_2.12-3.2.0.jar

RUN curl -fL \
    https://repo1.maven.org/maven2/io/delta/delta-storage/3.2.0/delta-storage-3.2.0.jar \
    -o /opt/spark/jars/delta-storage-3.2.0.jar


# ============================================================
# Hadoop / Azure Storage
# ============================================================

RUN curl -fL \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.3.4/hadoop-azure-3.3.4.jar \
    -o /opt/spark/jars/hadoop-azure-3.3.4.jar

RUN curl -fL \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure-datalake/3.3.4/hadoop-azure-datalake-3.3.4.jar \
    -o /opt/spark/jars/hadoop-azure-datalake-3.3.4.jar


# ============================================================
# Azure Event Hubs
# ============================================================

RUN curl -fL \
    https://repo1.maven.org/maven2/com/microsoft/azure/azure-eventhubs-spark_2.12/2.3.22/azure-eventhubs-spark_2.12-2.3.22.jar \
    -o /opt/spark/jars/azure-eventhubs-spark_2.12-2.3.22.jar

RUN curl -fL \
    https://repo1.maven.org/maven2/com/microsoft/azure/azure-eventhubs/3.3.0/azure-eventhubs-3.3.0.jar \
    -o /opt/spark/jars/azure-eventhubs-3.3.0.jar

RUN curl -fL \
    https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/1.0.2/scala-java8-compat_2.12-1.0.2.jar \
    -o /opt/spark/jars/scala-java8-compat_2.12-1.0.2.jar

RUN curl -fL \
    https://repo1.maven.org/maven2/org/apache/qpid/proton-j/0.33.8/proton-j-0.33.8.jar \
    -o /opt/spark/jars/proton-j-0.33.8.jar
    
# ============================================================
# Default command
# ============================================================

CMD ["/opt/spark/bin/spark-submit", "/app/streaming/spark_streaming_job.py"]