import os

from dotenv import load_dotenv

load_dotenv()

RESOURCE_GROUP = os.getenv("RESOURCE_GROUP")

STORAGE_ACCOUNT = os.getenv("STORAGE_ACCOUNT")

BRONZE_CONTAINER = os.getenv("BRONZE_CONTAINER")
SILVER_CONTAINER = os.getenv("SILVER_CONTAINER")
GOLD_CONTAINER = os.getenv("GOLD_CONTAINER")
CHECKPOINT_CONTAINER = os.getenv("CHECKPOINT_CONTAINER")

EVENTHUB_NAMESPACE = os.getenv("EVENTHUB_NAMESPACE")
EVENTHUB_NAME = os.getenv("EVENTHUB_NAME")
EVENTHUB_CONSUMER_GROUP = os.getenv("EVENTHUB_CONSUMER_GROUP")

EVENTHUB_CONNECTION_STRING = os.getenv("EVENTHUB_CONNECTION_STRING")